### ISSUE TITLE
Get status in roster

### ISSUE THREAD

**Issue by baliganikhil** [maxpowel/jQuery-XMPP-plugin#13]
When I want to get the roster, I get the id, name and subscription. Is it possible to get the status (available, dnd, away etc.) along with that as well? This is very useful when building and showing a list of friends along with their status icon like typical chat systems

**Comment by maxpowel** [comment]
The roster is just del contact list and does not have this information. Your server should send to you the connected list but I added a metod to force this task.
Define a listener for the onPresence event (as in the examples) and once you are connected, call the method getPresence. This method request presences that are handled by onPresence.

This method is provided in my last commit, dont forget pull.
It works for you?
