### ISSUE TITLE
Not working in Internet Explorer

### ISSUE THREAD

**Issue by shaundon** [maxpowel/jQuery-XMPP-plugin#15]
I'm unable to connect to anything using Internet Explorer (any version). 
No errors appear, it just doesn't do anything when clicking the Connect button.

Is this a known issue?

**Comment by maxpowel** [comment]
Sorry, I dont have windows so I can't test it. Can you provide any trace?

**Comment by shaundon** [comment]
Sure. I can try - although annoyingly it doesn't really fail with any error messages, it just doesn't do anything! IE is a pain..

**Comment by shaundon** [comment]
I've done some tests and I'm wondering if maybe this is being affected by same origin policy? A small demo page, which connects to my XMPP service when the page loads works fine up until around line 64 of jquery.xmpp.js, the `$.post` part:

``` javascript
//Init connection
var msg = "<body rid='"+this.rid+"' xmlns='http://jabber.org/protocol/httpbind' to='"+domain+"' xml:lang='en' wait='60' hold='1' content='text/xml; charset=utf-8' ver='1.6' xmpp:version='1.0' xmlns:xmpp='urn:xmpp:xbosh'/>";
$.post(this.url,msg,function(data){
```

I don't get any error at all for this, it's just simply that nothing happens. I added a quick `alert("foo")` just inside the call to `$.post` and this never gets executed, so it looks like this line is where the script stops.

The URL it's posting to is the http-bind module on my server, ie http://my.server.com:5280/http-bind

**Comment by shaundon** [comment]
Ok, I've fixed the issue now. It was indeed due to same origin policy. I've added the line `$.support.cors = true`  to the top of jquery.xmpp.js, which allows the connection to be initialised in IE.

I could contribute this to the project if you like - I'll add a comment to the top to explain what the line does and when it should be commented out.

**Comment by maxpowel** [comment]
Thank you!
If you want you can send a pull request and you will appear as the author of the fix ;)
Also I can do the modification and pull it

**Comment by shaundon** [comment]
Sure, I'll do it shortly. 

It turned out that the fix wasn't as simple as I first said - that only worked when I was running the script from a file:// link. When used on a server, I had to include some more code that intercepts the AJAX request if it's coming from IE, and then sends it via IE's XDomainRequest function that supports CORS.

**Comment by novomanish** [comment]
It doesn't work on IE 8. The error is "Invalid Credentials"
Same credentials work on FF and Chrome and Safari. FYI: My server is on same domain

**Comment by mayursnarole** [comment]
Hello Shaundon,
Is it now working on IE. Because I have downloaded the plugin but it is not working on IE.

**Comment by shaundon** [comment]
@mayursnarole it is or isn't working on IE?

**Comment by mayursnarole** [comment]
it is not working on IE..

**Comment by shaundon** [comment]
@maxpowel might be better placed to fix this - I don't have access to IE anymore.

**Comment by mithusree** [comment]
Please consider the issue #31 also for the next fix

**Comment by maxpowel** [comment]
Im not expert in IE but I am going to try to fix it
