### ISSUE TITLE
Messages don't have the type attribute

### ISSUE THREAD

**Issue by ghost** [maxpowel/jQuery-XMPP-plugin#2]
Good job with this plugin, is really good, but I found that the message object doesn't have the type attribute. This is importante, because you can know and work with different type of messages in diferent ways.

Greets!

**Comment by maxpowel** [comment]
Thank you!
I'm working on add support for this (and other) attribute. 
Thanks for your suggestion ;)

**Comment by maxpowel** [comment]
Hi! I have commit some updates.
When you send the message you can add any attribute:
.sendMessage({body: "Hi",to: "someone@somewhere.com",type: "chat",otherAttr: "value"});
All attributes will be added to the xmpp tag "message".

If you want to send an error, the sendMessage could be:
.sendMessage({to: "someone@somewhere.com",type: "error",}, "<error code="503" type="cancel"><service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error>");

When you receive a message:
.onMessage: function(message){
     if(message.attributes['error'])
     console.log("Error code: "+message.data.find("error").attr("code"));
}

Has been added two properties to the message object:
attributes: all atributes of the tag message
data: The other data sent from de server (like error information)

If this method is easy to use, I will add it to iq and presence.

**Comment by maxpowel** [comment]
I forgot that I cant use html in the comments :P
When I wrote
If you want to send an error, the sendMessage could be:
.sendMessage({to: "someone@somewhere.com",type: "error",}, "");
It should be:
If you want to send an error, the sendMessage could be:
.sendMessage({to: "someone@somewhere.com",type: "error"}, "[error code="503" type="cancel"][service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/][/error]");

Changing the [ ] for < >

The second parameter is the extra data that you want to add in the message.

Hope I have not more error. If you need it, I can do some working examples
