### ISSUE TITLE
Does it support Group chat

### ISSUE THREAD

**Issue by novomanish** [maxpowel/jQuery-XMPP-plugin#23]
How can we have group chat by using this library?

**Comment by golfixe** [comment]
yes support...

**Comment by maxpowel** [comment]
The library is sematic independent of the messages. You can manage group chat without any problem (your server should support group chat)

**Comment by novomanish** [comment]
thanks

**Comment by quicknetsoft** [comment]
can you give example of group chat using this plugin

**Comment by suchidomelo** [comment]
can you give example of group chat using this plugin please

**Comment by suchidomelo** [comment]
i m use openfire xmpp , give example of group chat using this plugin
