### ISSUE TITLE
Difference between current version and one referenced in example

### ISSUE THREAD

**Issue by goojo** [maxpowel/jQuery-XMPP-plugin#3]
The example code references http://jair.lab.fi.uva.es/~alvagar/jQuery-XMPP-plugin/jquery.xmpp.js but the example does not work with the current version of jquery.xmpp.js 

By not work I mean "sendMessage" does nothing. 

Hope this helps. 

John

**Comment by maxpowel** [comment]
I'm going to fix it, thank you for the notice ;)

**Comment by maxpowel** [comment]
Hi! Hi have fixed the references. I have tested it and seems it works, also is right for you?
