### ISSUE TITLE
Google Chrome does not execute disconnect on window beforeunload event

### ISSUE THREAD

**Issue by asghonim** [maxpowel/jQuery-XMPP-plugin#6]
Hello,
I am new to XMPP and was developing a simple chat client similar to your example. I wanted to hook an event with window unload to close the connection with XMPP server. So, I did something like this

   function leaving()
   {
                    alert('disconnecting');
                   $.xmpp.disconnect();

   }
window.addEventListener("beforeunload", leaving, false);

The above code worked fine on Firefox 12.0, but on Google chrome 19, the alert is blocked (meaning the event was called) but the XMPP connection never closed.

So, I did some digging and found out the reason. In your code in the the function $.xmpp.disconnect, you use $.post to send the request to the server. $.post uses the asynchronous version of $.ajax. If you change this to use synchronous ajax, Google chrome correctly disconnects the xmpp connection before closing the page. This is the code that worked for me

$.ajax({
type: 'POST',
url: this.url,
data: msg,
success: function(data){
xmpp.connections = xmpp.connections - 1;
xmpp.messageHandler(data);
xmpp.listening = false;
//Do not listen anymore!
//Two callbacks
if(callback != null)
callback(data);
if(xmpp.onDisconnect != null)
xmpp.connected = false;
xmpp.onDisconnect(data);
},
dataType: 'text',
async:false   // THIS IS THE FIX
});

My suggestion is that you take a parameter in the disconnect function to specify whether the call should be synchronous or asynchronous 

Hope this helps someone else with the same issue!
Regards,

**Comment by maxpowel** [comment]
Sorry for late! I'm in exam period and I can't check for new all I want.
Thank you for your excelent work ;)

**Comment by asghonim** [comment]
Thank you for your great project ;)

**Comment by maxpowel** [comment]
Issue closed
